apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: metric-source
  namespace: default
labels:
  app: metric-source
spec:
  selector:
    matchLabels:
      app: metric-source
  podMetricsEndpoints:
  - port: metrics
    interval: 15s
