apiVersion: monitoring.coreos.com/v1alpha1
kind: PrometheusAgent
metadata:
  name: collector
  namespace: default
  labels:
    prometheus: collector
spec:
  serviceAccountName: promagent-collector
  image: quay.io/prometheus/prometheus:v2.50.1
  podMonitorSelector:
    matchLabels:
      app: metric-source
  resources:
    requests:
      memory: "400Mi"
      cpu: "200m"
    limits:
      memory: "400Mi"
      cpu: "200m"
  shards: 2
  remoteWrite:
    - url: http://prometheus-receiver.remote.svc:9090/api/v1/write
---

