apiVersion: monitoring.coreos.com/v1alpha1
kind: PrometheusAgent
metadata:
  name: collector
  namespace: prometheus-op-system
  labels:
    prometheus: collector
spec:
  serviceAccountName: promagent-collector
  image: quay.io/prometheus/prometheus:v2.50.1
  podMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      app: metric-source
  resources:
    requests:
      memory: "400Mi"
      cpu: "200m"
    limits:
      memory: "400Mi"
      cpu: "200m"
  shards: 2
  remoteWrite:
    - url: http://prometheus-receiver.remote.svc:9090/api/v1/write
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: metric-source
  namespace: default
  labels:
    app: metric-source
spec:
  selector:
    matchLabels:
      app: metric-source
  podMetricsEndpoints:
    - port: metrics
      interval: 15s
