apiVersion: monitoring.coreos.com/v1alpha1
kind: PrometheusAgent
metadata:
  name: collector
  namespace: prometheus-op-system
  labels:
    prometheus: collector
spec:
  serviceAccountName: promagent-collector
  image: quay.io/prometheus/prometheus:v2.50.1
  podMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      app: metric-source
  resources:
    requests:
      memory: "400Mi"
      cpu: "200m"
    limits:
      memory: "400Mi"
      cpu: "200m"
  shards: 2
  remoteWrite:
    - url: http://prometheus-receiver.remote.svc:9090/api/v1/write
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: metric-source
  namespace: default
  labels:
    app: metric-source
spec:
  selector:
    matchLabels:
      app: metric-source
  podMetricsEndpoints:
    - port: metrics
      interval: 15s
---
apiVersion: rbac.authorization.k8s.io/v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: collector
    namespace: default
  rules:
  - apiGroups:
    - ""
    resources:
    - services
    - endpoints
    - pods
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - extensions
    resources:
    - ingresses
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - networking.k8s.io
    resources:
    - ingresses
    verbs:
    - get
    - list
    - watch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: collector
    namespace: kube-system
  rules:
  - apiGroups:
    - ""
    resources:
    - services
    - endpoints
    - pods
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - extensions
    resources:
    - ingresses
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - networking.k8s.io
    resources:
    - ingresses
    verbs:
    - get
    - list
    - watch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: collector
    namespace: prometheus-op-system
  rules:
  - apiGroups:
    - ""
    resources:
    - services
    - endpoints
    - pods
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - extensions
    resources:
    - ingresses
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - networking.k8s.io
    resources:
    - ingresses
    verbs:
    - get
    - list
    - watch
kind: RoleList
---
apiVersion: rbac.authorization.k8s.io/v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: collector
    namespace: default
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: collector
  subjects:
  - kind: ServiceAccount
    name: promagent-collector
    namespace: prometheus-op-system
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: collector
    namespace: kube-system
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: collector
  subjects:
  - kind: ServiceAccount
    name: promagent-collector
    namespace: prometheus-op-system
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: collector
    namespace: prometheus-op-system
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: collector
  subjects:
  - kind: ServiceAccount
    name: promagent-collector
    namespace: prometheus-op-system
kind: RoleBindingList