apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: prometheus
  name: prometheus
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "discovery.k8s.io"
    resources:
      - endpointslices
    verbs:
      - get
      - list
      - watch
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: prometheus
  name: prometheus
subjects:
  - kind: ServiceAccount
    name: default
    namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-shard-1
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
      shard: "1"
  template:
    metadata:
      labels:
        app: prometheus
        shard: "1"
    spec:
      containers:
        - name: prometheus
          image: quay.io/prometheus/prometheus:v2.50.1
          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --web.listen-address=:9090
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus
          resources:
            requests:
              memory: "400Mi"
              cpu: "100m"
            limits:
              memory: "500Mi"
              cpu: "200m"
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-shard-1-cfg
            defaultMode: 420
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-shard-1-cfg
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'metric-source'
        kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
            - default
        relabel_configs:    
          - source_labels: [__meta_kubernetes_service_label_app, __meta_kubernetes_service_labelpresent_app]
            separator: ;
            regex: (avalanche);true
            replacement: $1
            action: keep
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            separator: ;
            regex: metrics
            replacement: $1
            action: keep
          - source_labels: [__meta_kubernetes_namespace]
            separator: ;
            regex: (.*)
            target_label: namespace
            replacement: $1
            action: replace
          - source_labels: [__meta_kubernetes_pod_name]
            separator: ;
            regex: (.*)
            target_label: pod
            replacement: $1
            action: replace
          - source_labels: [__meta_kubernetes_pod_container_name]
            separator: ;
            regex: (.*)
            target_label: container
            replacement: $1
            action: replace
          - action: hashmod
            source_labels: [__address__]
            modulus: 2
            target_label: __tmp_hashmod
          - action: keep
            source_labels: [__tmp_hashmod]
            regex: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-shard-2
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
      shard: "2"
  template:
    metadata:
      labels:
        app: prometheus
        shard: "2"
    spec:
      containers:
        - name: prometheus
          image: quay.io/prometheus/prometheus:v2.50.1
          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --web.listen-address=:9090
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus
          resources:
            requests:
              memory: "400Mi"
              cpu: "100m"
            limits:
              memory: "500Mi"
              cpu: "200m"
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-shard-2-cfg
            defaultMode: 420
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-shard-2-cfg
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'metric-source'
        kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
            - default
        relabel_configs:    
          - source_labels: [__meta_kubernetes_service_label_app, __meta_kubernetes_service_labelpresent_app]
            separator: ;
            regex: (avalanche);true
            replacement: $1
            action: keep
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            separator: ;
            regex: metrics
            replacement: $1
            action: keep
          - source_labels: [__meta_kubernetes_namespace]
            separator: ;
            regex: (.*)
            target_label: namespace
            replacement: $1
            action: replace
          - source_labels: [__meta_kubernetes_pod_name]
            separator: ;
            regex: (.*)
            target_label: pod
            replacement: $1
            action: replace
          - source_labels: [__meta_kubernetes_pod_container_name]
            separator: ;
            regex: (.*)
            target_label: container
            replacement: $1
            action: replace
          - action: hashmod
            source_labels: [__address__]
            modulus: 2
            target_label: __tmp_hashmod
          - action: keep
            source_labels: [__tmp_hashmod]
            regex: 2
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
spec:
  clusterIP: None
  selector:
    app: prometheus
  ports:
    - name: web
      port: 9090
