apiVersion: v1
kind: Namespace
metadata:
  name: remote
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-receiver
  namespace: remote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-receiver
  template:
    metadata:
      labels:
        app: prometheus-receiver
    spec:
      containers:
      - name: prometheus
        image: quay.io/prometheus/prometheus
        args:
        - --web.enable-remote-write-receiver
        - --config.file=/etc/prometheus/prometheus.yml
        - --web.listen-address=:9090
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
      volumes:
      - name: config-volume
        configMap:
          name: prometheus-cfg
          defaultMode: 420
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-receiver
  namespace: remote
spec:
  clusterIP: None
  selector:
    app: prometheus-receiver
  ports:
  - name: web
    port: 9090
---
# self-scrape config
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-cfg
  namespace: remote
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'prometheus-receiver'
        static_configs:
          - targets: ['localhost:9090']
