apiVersion: apps/v1
kind: Deployment
metadata:
  name: metric-source
  labels:
    app: metric-source
spec:
  replicas: 2
  selector:
    matchLabels:
      app: metric-source
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: metric-source
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - metric-source
                topologyKey: kubernetes.io/hostname
      containers:
        - image: quay.io/prometheuscommunity/avalanche:main
          name: avalanche
          imagePullPolicy: IfNotPresent
          args:
            - --metric-count=1
            - --series-count=10
            - --port=9001
          ports:
            - containerPort: 9001
              protocol: TCP
              name: metrics
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: metric-source
  labels:
    app: metric-source
spec:
  ports:
    - name: metrics
      port: 9001
      protocol: TCP
      targetPort: metrics
  selector:
    app: metric-source
  type: ClusterIP
