apiVersion: v1
kind: Service
metadata:
  name: avalanche
  labels:
    app: avalanche
spec:
  ports:
    - name: metrics
      port: 9001
      protocol: TCP
      targetPort: metrics
  selector:
    app: avalanche
  type: ClusterIP
